/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useState} from 'react'
import {useGLTF,useTexture} from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('assets/floor.gltf')
  return (
    <group  rotation={[0, 0, 0]}
            position={[0, -0.1, 0]}
            receiveShadow ref={group} {...props} dispose={null}>
      <mesh material={materials['Material.001']} geometry={nodes.Plane.geometry} scale={[10, 10, 10]} />
    </group>
  )
}

useGLTF.preload('assets/floor.gltf')
